swagger: '2.0'
info:
  title: API de Transactions ArgentBank
  version: 1.0.0
paths:
  /transactions:
    get:
      summary: Récupérer toutes les transactions du mois en cours
      description: |
        Récupère une liste de transactions regroupées par compte pour le mois en cours.
      responses:
        200:
          description: Réponse réussie avec les données des transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        404:
          description: Aucune transaction trouvée pour le mois en cours
    post:
      summary: Ajoute une nouvelle transaction
      parameters:
        - name: body
          in: body
          description: Objet JSON représentant les détails de la transaction à ajouter
          required: true
          schema:
            $ref: '#/definitions/TransactionInput'
      responses:
        200:
          description: La transaction a été ajoutée avec succès
        400:
          description: Les données fournies sont invalides

  /transactions/{id}:
    parameters:
      - name: id
        in: path
        description: ID de la transaction pour récupérer les détails
        required: true
        type: string
    get:
      summary: Récupérer les détails d'une transaction spécifique
      responses:
        200:
          description: Réponse réussie avec les détails de la transaction
          schema:
            $ref: '#/definitions/Transaction'
        404:
          description: Transaction non trouvée

    put:
      summary: Mettre à jour les détails d'une transaction spécifique
      parameters:
        - name: id
          in: path
          description: ID de la transaction à mettre à jour
          required: true
          type: string
        - name: body
          in: body
          description: Données de transaction mises à jour
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        200:
          description: Transaction mise à jour avec succès
        400:
          description: Corps de requête invalide
        404:
          description: Transaction non trouvée

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: number
        description: Montant de la transaction
      account:
        type: string
        description: Compte associé à la transaction
  TransactionInput:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: number
        description: Montant de la transaction
      account:
        type: string
        description: Compte associé à la transaction
